### ISSUE TITLE
Redirect http traffic on schema.ocf.io

### ISSUE THREAD

**Issue by floydtree** [ocsf/ocsf-server#12]
It doesn't look like we have enabled redirection of http traffic to https on schema.ocsf.io

Currently, if you navigate to http://schema.ocsf.io, it doesn't respond (good that it doesn't accept port 80 connections), but we should be redirecting such to 443 instead, for a seamless experience.

**Comment by rroupski** [comment]
I open the http port again. I don't think we should redirect it to https. For example, MITRE has http port open: http://attack.mitre.org/

**Comment by floydtree** [comment]
Why not redirect? I don't think what MITRE does or does not do, should inform our methods. Redirection of http to https traffic is very common and a recommended practice.

**Comment by rroupski** [comment]
why should I redirect? more work for no extra value.

**Comment by floydtree** [comment]
1. Validation API use-case, there is an off chance that folks might send real log data (which can be potentially sensitive) to the server in the hopes of performing validation, potentially utilizing port 80, leading to a scenario where the logs are now sent using an unencrypted channel. We should control the aspects that we can.
2. Given, OCSF is a security-first schema framework, an Industry leading effort built and maintained by major Security vendors, it's the least we can do to uphold the expectation that is otherwise set from the non-security community.

**Comment by rroupski** [comment]
done
