### ISSUE TITLE
https://schema.ocsf.io/api/base_event does not return "requirement" key for every attribute.

### ISSUE THREAD

**Issue by dfederschmidt** [ocsf/ocsf-server#17]
It seems that `https://schema.ocsf.io/api/base_event` does not return the `requirement` property for 
- unmapped
- count
- start_time 

I don't see why these would not have a corresponding requirement property, so raising this here. Thanks! 

EDIT: Just discovered there are also a couple of others missing this property beyond the ones mentioned above.

**Comment by rroupski** [comment]
The default value of the `requirement` property is `optional`, thus it is often not set in the schema files.
