### ISSUE TITLE
Set "Access-Control-Allow-Headers" for validate endpoint

### ISSUE THREAD

**Issue by dfederschmidt** [ocsf/ocsf-server#20]
Follow-up from #16 

In order to use the `/api/validate` endpoint from browser context, the 
`Access-Control-Allow-Headers` should be set to allow for the `Content-Type` header to be submitted by the client. The request works without a content-type set but fails if `Content-Type: application/json` is passed explicitly.

**Comment by dfederschmidt** [comment]
Adding on to this issue - it seems like the `/api/validate` endpoint returns different results based on whether the content-type is specified or not.

To reproduce:

```python
import requests
import json

url = "https://schema.ocsf.io/api/validate"

res = requests.post(url, data=json.dumps({"class_uid": 333}))
print(res.request.headers)
print(res.json())
```
yields:
```
{'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '18'}
{'error': 'Missing class_uid'}
```

This should be false, given there is a `class_uid` provided. Then, adding the content type header, the result becomes correct.

```
import requests
import json

url = "https://schema.ocsf.io/api/validate"

res = requests.post(url, json={"class_uid": 333})
print(res.request.headers)
print(res.json())

```
yields:
```
{'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '18', 'Content-Type': 'application/json'}
{'error': 'Unknown class_uid: 333', 'value': 333}
```

@rroupski-splunk  thoughts?

**Comment by rroupski** [comment]
The first example with a missing content-type header -- the payload data is not decoded as json therefore the `class_uid` cannot be "found" in the payload, so the `{'error': 'Missing class_uid'}` is correct.

The second example with a correct content-type header returns `{'error': 'Unknown class_uid: 333', 'value': 333}`, which is also correct -- the class uid 333 is unknown/not defined by the schema.
