### ISSUE TITLE
Support user-defined data types

### ISSUE THREAD

**Issue by rroupski** [ocsf/ocsf-server#27]
Using extension to add new data types (already supported) or to extend existing data types (add contains or data examples).

#### For example:
The schema defines `country` attribute as a string (the country code, as defined by the ISO 3166-1 standard -- Alpha-2 code). However, some users would like to use a stricter definition, such as a list of country codes. This could be achieved by defining a new type, `country_code_t`, which is a subtype of `string_t`, and lists the valid values.

```json
  "country_code_t": {
    "caption": "Country Code",
    "description": "Defined by the ISO 3166-1 standard -- Alpha-2 code. For example: <code>AA</code>.",
    "type": "string_t",
    "values": ["AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "..."]
  },
```

Then, the data new type can be used to overwrite the dictionary definition of the country attribute:

```json
{
  "country": {
    "type": "country_code_t"
  }
}
```

**Comment by rroupski** [comment]
done in 2.48.0

**Comment by wjdingman1** [comment]
okay i see this now, thanks again 👍
