### ISSUE TITLE
JSON Schema Generator automatically including all profiles

### ISSUE THREAD

**Issue by wjdingman1** [ocsf/ocsf-server#36]
When generating the JSON Schema for an `inventory_info` event, it appears that profiles are added even if they aren't included as a query parameter.

This causes the `cloud` profile to be added and makes the `cloud` object a required field. This ultimately invalidates the schema for an `inventory_info` event that does not originate in the cloud.

See -> `curl -X GET "https://schema.ocsf.io/schema/classes/inventory_info" -H "accept: application/json"`

![image](https://github.com/ocsf/ocsf-server/assets/37029691/eaf15099-090f-4265-959d-9c694b2cfa91)

**Comment by rroupski** [comment]
This is by design. It allows getting all attributes, including attributes from the applicable profiles, without explicitly listing the profiles.

If you want to get a class or object without any profiles, then use the `profiles` query parameter. For example:
```shell
curl -X GET "https://schema.ocsf.io/schema/classes/inventory_info?profiles=" -H "accept: application/json"
```

```json
{
  "required": [
    "type_uid",
    "category_uid",
    "device",
    "metadata",
    "class_uid",
    "severity_id",
    "time",
    "activity_id"
  ]
}
```

**Comment by wjdingman1** [comment]
ah so you need to explicitly say `profiles=` got it, thanks

**Comment by wjdingman1** [comment]
@rroupski  

Hey I had a follow-up question on this. When I supply `profiles=` then `cloud` is removed from the event class schema as intended. 

But this also removes profiles that I have defined on objects within this event class, is that the intended behavior?

Even when I supply `profiles=foo` and foo is a profile on `Device` object, it is not present?

Is this just a limitation because it is the event class schema? If so, is there a way to propagate the supplied profiles to objects within the event class?
