### ISSUE TITLE
Date/Time profile captions generation

### ISSUE THREAD

**Issue by wjdingman1** [ocsf/ocsf-server#43]
When applying the Date/Time profile to an object the captions for the `datetime_t` fields are not derived from the original `timestamp_t` attribute.

![image](https://github.com/ocsf/ocsf-server/assets/37029691/a1082377-4983-463b-96c5-2de5d4d1d591)

**Comment by rmouritzen-splunk** [comment]
Can you explain more? 

I assume you're talking about the Description field of the table, and this shows the description of the original attribute. It does not show the description of the data type, but that is never done. The data type descriptions are only shown over on the "Data Types" page.

In any case, if you could show the actual versus the expected, it would help me understand this issue.

**Comment by wjdingman1** [comment]
Hey sorry, I should have been more descriptive. This is a view of the device object, which has`timestamp_t` fields:

- `modified_time`
-  `created_time`
- `first_seen_time`
- `last_seen_time`

When the `Date/Time` profile is applied, then the expected behavior is that the `datetime_t` versions of these fields are also shown in the browser, with the proper caption, name etc.

| Caption | Name | Requirement | Type | Description
| --- | --- | --- | --- | --- |
| Created Time  | created_time_dt  | Optional | Datetime | The time when the device was known to have been created. |
| Created Time  | created_time  | Optional | Timestamp | The time when the device was known to have been created. |

Instead of 

| Caption | Name | Requirement | Type | Description
| --- | --- | --- | --- | --- |
| created_time  | created_time_dt  | Optional | String | The time when the device was known to have been created. |
| Created Time  | created_time  | Optional | Timestamp | The time when the device was known to have been created. |

We can see this behavior when running an extension that has added some additional fields to an object and the object has `timestamp_t` fields from the base schema.

**Comment by wjdingman1** [comment]
you know what, after forcing myself to double-check a few things this was of course a user error, please ignore, thank you 👍
