### ISSUE TITLE
Add a filter recommended attributes in the class, object, profile view

### ISSUE THREAD

**Issue by floydtree** [ocsf/ocsf-server#47]
Currently, the sever offers a drop down filter for optional attributes, it will be great to have a filter for recommended attributes as well. Something similar to - 
![Screenshot 2023-10-18 at 3 44 49 PM](https://github.com/ocsf/ocsf-server/assets/89877409/7eebf25e-2de2-4543-b86e-f84ca71756ed)

**Comment by mikeradka** [comment]
Ack, can take a look now that i understand better how this dropdown works.
