### ISSUE TITLE
Missing requirement property in the JSON schema

### ISSUE THREAD

**Issue by floydtree** [ocsf/ocsf-server#54]
When the OCSF server renders a JSON schema for an event class, it does NOT add a requirement property if the underlying json definition of the schema doesn't explicitly add a requirement.

Note that, while defining the schema json files, missing requirement implies it is optional, but that is not translated to the JSON schema that the server consequently renders.

Example object - [Metadata object definition](https://github.com/ocsf/ocsf-schema/blob/main/objects/metadata.json#L28)

Example json schema - 

```
      "modified_time": {
        "type": "timestamp_t",
        "description": "The time when the event was last modified or enriched.",
        "caption": "Modified Time",
        "_source": "metadata",
        "type_name": "Timestamp"
      }
 ```

**Comment by rmouritzen-splunk** [comment]
FYI @floydtree: Moved here to `ocsf-server` since the remaining work is in this project.
