### ISSUE TITLE
Dictionary cross-references are not shown for attributes that are overridden from Base Event

### ISSUE THREAD

**Issue by pagbabian-splunk** [ocsf/ocsf-server#63]
As an example, `status` `status_id` `status_detail` are overridden in `Detection Finding` but when showing them in the browser, only `Base Event` is cross-referenced.

**Comment by rmouritzen-splunk** [comment]
Per discussion with @pagbabian-splunk, we also want to show where attributes are first included in a class or object, and where they are overridden.

**Comment by rmouritzen-splunk** [comment]
Fixed. Issue #71 created for to fix the representation of "source" accurately for objects.
