### ISSUE TITLE
Clicking "JSON Schema" from "Base Event" page leads to 404

### ISSUE THREAD

**Issue by rmouritzen-splunk** [ocsf/ocsf-server#70]
# Steps to reproduce:
1. Click on "Base Event" from navigation. This leads to the special `/base_event` URL.
2. Click on "JSON Schema".

This results in a 404. Note that navigating from `/class/base_event` works. This URL can be navigated to from a few location, including from the class list on the "Classes" page.

# Cause
This is happening because the JSON Schema JavaScript in `priv/static/js/app.js` is navigating to `/schema/base_event`, which doesn't exist. When navigating from a `/classes/<class_name>` URL, the JavaScript function leads to the working `/schema/classes/base_event` URL.

# Possible fixes
There are (at least) two ways to fix:
1. Fix the JavaScript function to handle coming from the `/base_event` URL.
2. Remove the special `/base_event` URL entirely from the OCSF Server since it is equivalent to `/classes/base_event`. This is a larger change, but could result in a overall cleaner solution.

**Comment by floydtree** [comment]
I am in favor of removing the additional /base_event url from the server, since an alternative already exists if people want to look at the base event. And as you said, it's definitely a much cleaner solution.
