### ISSUE TITLE
Redesign Profile Implementation

### ISSUE THREAD

**Issue by floydtree** [ocsf/ocsf-server#9]
Background: A few things broke in our testing pipelines when working with the [Network Activity class schema](https://github.com/ocsf/ocsf-schema/blob/main/events/network/network.json), it turns out the class now includes 5 profiles (“cloud”, “domain_security”, “host”, “malware”, “user”), which basically add the attributes as defined in the profile definitions to the rendered schema by default. These definitions then define requirements for the attributes within. For example, this is how the [malware profile](https://github.com/ocsf/ocsf-schema/blob/main/profiles/malware.json) looks like.
With this example in mind, now if you query for a [network_activity class schema in the browser](https://schema.ocsf.io/api/classes/network_activity), you’ll get a JSON schema that includes all the attributes defined in the profile, which includes additional required fields that you don’t really require to normalize a network activity log. With the malware profile, it adds `disposion_id` & `disposion` as required fields (side note - there appears to be a spelling mistake in this attribute, assuming it is `disposition_id`)
Thus, even if, I as a user do NOT want malware profile for my network_activity class schema, I am forced with the requirement to populate/map `disposion_id`, else my data will technically be non-compliant with OCSF, which doesn’t make sense.
Additionally, there is a disconnect between browser view and the actually rendered JSON schema, the JSON seems to by default include all profile attributes regardless of what you choose in the browser via the checkboxes. So the checkboxes give false sense of control to the user.

In summary, profiles appear to have become a compulsive factor instead allowing for originally intended freedom.

-------

From my understanding, it boils down to how profiles are defined in the event_class (as includes in the [JSON definitions](https://github.com/ocsf/ocsf-schema/blob/23280a2baeb3df0381114b8924a7c3bc4a1b44d0/events/network/network.json#L16) of the event_class)

I think the way it should be implemented is,
You shouldn’t define profiles in the JSON class definitions at all, instead the profile selection should an api parameter where you can explicitly mention which profiles you want for any desired  event_class. The same can be translated in the browser in the form of checkboxes.

If no profiles are mentioned the user must be presented with the vanilla definition of the event_class both in the browser & in the actual JSON schema. Profiles should only be added (i.e. the attributes defined in the profiles), when explicitly selected in the api/browser.

**Comment by rroupski** [comment]
Rajas, is there anything else to do for this issue?

**Comment by floydtree** [comment]
We should be good with the API enhancements, especially considering we are sticking the profile definition in the event class schema.
